# Generated by Django 5.1.3 on 2024-12-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_contact_alter_favouritenstockwatch_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouritenstockwatch',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favouritenstockwatch',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
